"""Add player contact and emergency fields

Revision ID: 6e1c049f7419
Revises: 75c4a00a8ba2
Create Date: 2026-02-02 15:41:12.785907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1c049f7419'
down_revision: Union[str, None] = '75c4a00a8ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('contact_number', sa.String(), nullable=True))
    op.add_column('players', sa.Column('address', sa.String(), nullable=True))
    op.add_column('players', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('emergency_contact_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'emergency_contact_number')
    op.drop_column('players', 'emergency_contact_name')
    op.drop_column('players', 'address')
    op.drop_column('players', 'contact_number')
    # ### end Alembic commands ###
