"""Add player level and club settings

Revision ID: 75c4a00a8ba2
Revises: 001
Create Date: 2026-02-01 23:35:12.004860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c4a00a8ba2'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranking_system_type', sa.Enum('int_range', 'letter_range', 'custom', name='rankingsystemtype'), nullable=True),
    sa.Column('int_range_start', sa.Integer(), nullable=True),
    sa.Column('int_range_end', sa.Integer(), nullable=True),
    sa.Column('letter_range_start', sa.String(), nullable=True),
    sa.Column('letter_range_end', sa.String(), nullable=True),
    sa.Column('custom_levels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_settings_id'), 'club_settings', ['id'], unique=False)
    op.add_column('players', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'level')
    op.drop_index(op.f('ix_club_settings_id'), table_name='club_settings')
    op.drop_table('club_settings')
    # ### end Alembic commands ###
