"""Add is_temp field to Player model

Revision ID: ea9559bdeae1
Revises: 6e1c049f7419
Create Date: 2026-02-05 22:55:40.784261

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea9559bdeae1'
down_revision: Union[str, None] = '6e1c049f7419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('players', sa.Column('is_temp', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute('UPDATE players SET is_temp = false WHERE is_temp IS NULL')
    
    # Make column non-nullable
    op.alter_column('players', 'is_temp', nullable=False, server_default=sa.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_temp')
    # ### end Alembic commands ###
